DWAPlannerROS:
  acc_lim_x: 0.4
  acc_lim_y: 0.0
  acc_lim_theta: 2.0
  acc_limit_trans: 0.15
  max_trans_vel: 0.5
  min_trans_vel: 0.1
  max_vel_x: 0.4
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 0.5
  min_rot_vel: 0.2
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.3
  sim_time: 3.0
  sim_granularity: 0.1
  angular_sim_granularity: 0.05
  vx_samples: 60
  vy_samples: 1
  vth_samples: 100
  path_distance_bias: 10.0
  goal_distance_bias: 8.0
  occdist_scale: 0.05
  forward_point_distance: 0.0
  stop_time_buffer: 0.3
  scaling_speed: 0.4 
  max_scaling_factor: 0.2
  oscillation_reset_dist: 0.5
  oscillation_reset_angle: 0.2
  sim_period: 3.0
  rot_stopped_vel: 0.1
  trans_stopped_vel: 0.02
   

  holonomic_robot: false
